name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish package
        uses: SuffolkLITLab/ALActions/publish@main
        with:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          VERSION_TO_PUBLISH: ${{ github.ref_name }}
